### PR TITLE
SIG Tracker Basic Web App

### PR DESCRIPTION
**Pull request by Saujas**
I have created a basic start to the web app for tracking SIGs. It currently has one class for list of different SIGs.

### CODE REVIEW

**Comment by Saujas** [comment]
Please suggest any changes that should be made.

**Comment by apb7** [comment]
Hi @Saujas, we already have the basic structure. I do not think we need all these files. Did you check the master branch and see which files are already present?

**Comment by Saujas** [comment]
Okay then, I'll modify the files in the master branch accordingly

**Comment by Saujas** [comment]
@apb7 could you review my code for indenting and patterns?

**Comment by sammy1997** [comment]
Please squash the commits. It's not a good practice to have 2 commits in a single PR

**Pull request closed without merging**
